# Generated by Django 4.1.7 on 2023-04-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeconsultationmodel',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
    ]
