# Generated by Django 4.1.7 on 2023-04-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lps', '0003_freeconsultationmodel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freeconsultationmodel',
            old_name='email',
            new_name='cemail',
        ),
        migrations.RenameField(
            model_name='freeconsultationmodel',
            old_name='mobilenumber',
            new_name='cmobilenumber',
        ),
    ]
