# Generated by Django 4.1.7 on 2023-04-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lps', '0004_rename_email_freeconsultationmodel_cemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeconsultationmodel',
            name='cmobilenumber',
            field=models.CharField(max_length=200),
        ),
    ]
