# Generated by Django 4.1.7 on 2023-04-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lps', '0005_alter_freeconsultationmodel_cmobilenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeconsultationmodel',
            name='iscontacted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
